name: Build and deploy CSS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build CSS
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout theme
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build CSS
        run: npm run build:css

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: "./"
          enable_jekyll: true
